apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: mi-springbootapp
        image: dariotroilo/personalpay:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: springapp-svc
#spec:
#  selector:
#    app: springbootapp
#  ports:
#    - protocol: TCP
#      port: 443
#      targetPort: 8080
#  type: LoadBalancer
